backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "Intro "
        name: "intro"
        file: "pages/intro.vue"
        fields:
          - {label: Intro, name: intro, widget: markdown}
          - {label: Subtitle, name: subtitle, widget: string}